README.md

Fix typo in code snippet

---

dev/App.vue
src/components/input-select/InputSelect.vue

/kind bug
Correct functionality of `input-select`
Fixes #7

Added missing attributes to select options.

---

package.json

/kind bug
Npm repo should have a link to Github
Fixes #6

Added Repo and Issues to package.json

---

.npmignore

/kind bug
For `npm install` to work normally after installing the package
Fixes #10

Try to ignore .git in all subfolders for npm

---

dev/App.vue
src/components/dynamic-form/DynamicForm.js
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/core/utils/form-control.model.js

/kind bug
Allow custom classes for for customization and grid
Fixes #16

Added  customClasses and fix small stuff

---

dev/App.vue
src/components/dynamic-form/DynamicForm.js
src/components/dynamic-form/DynamicForm.vue
src/core/utils/form-control.model.js

/kind api-change
Add support to Netlify Forms https://www.netlify.com/products/forms/ 
Fixes #18

Added Spread Form Options and netlify support

---

dev/App.vue
src/components/dynamic-input/DynamicInput.js
src/components/dynamic-input/DynamicInput.vue
src/core/utils/form-control.model.js

/kind api-change
Allow user to activate validation of errors on blur.
Fixes #21 
```release-note
```
```docs
```

Input autovalidation on blur

---

dev/App.vue
src/components/input-textarea/InputTextarea.vue
src/core/utils/form-control.model.js
src/styles/themes/default.scss

>
/kind bug
Fix textarea several issues such as event not been triggered and cols, rows attributes not  being  set.
Fixes #23

Fix textarea issues

---

CHANGELOG.md
package.json
src/components/input-textarea/InputTextarea.js

/kind bug
Messed up textarea
Fixes #29
```release-note
```
```docs
```

Hotfix textarea methods added

---

dev/App.vue
docs/guide/models.md
src/components/dynamic-input/DynamicInput.vue
src/core/utils/form-control.model.js
src/styles/themes/default.scss

>
/kind feature
Support for hint text on inputs.
Fixes #26

Helper text support

---

docs/guide/models.md

Add missing models to docs

---

docs/guide/validation.md

>
> /kind bug
> /kind desig
Fixes #
```release-note
NONE
```
```docs
```

Improved grammar

---

docs/guide/theming.md

>
> /kind bug
> /kind design
Fixes #
```release-note
NONE
```
```docs
```

Fix Variables available heading

---

.github/workflows/ci.yml
.github/workflows/release.yml
package.json

/kind bug
Npm publish was run twice giving a 403 error when merging. to master

fix(ci): add release job separately and removed publish script

---

docs/guide/examples/phone-prefix-example.md

>
> /kind bug
> /kind design
Fixes #
```release-note
NONE
```
```docs
```

fix(doc): corrected english spelling and grammar

---

.github/workflows/release.yml

/kind bug
Adds build to release ci workflow
Fixes #59

fix(ci): added build script to ci release workflow

---

.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.npmignore
api-extractor.json
package-lock.json
package.json

BREAKING CHANGE:  Declaration types are now generated using Microsoft api-extractor
>
/kind build
This should solve the issue `Cannot find module '@asigloo/vue-dynamic-forms' or its corresponding type declarations.` when importing the lib into a TS project.
Closes #44 
```release-note
```
```docs
```

feat(types): added automatic declaration types

---

.npmignore
rollup.config.js
vue.config.js

Bugfix/fix 88 module parse failed unexpected token 

---

src/components/dynamic-form/DynamicForm.vue
tsconfig.json

>
> /kind bug
> /kind design
> /kind documentation
Fixes #88 
```release-note
```
```docs
```

fix(build): fix optional chaining error on builds

---

README.md
package-lock.json
package.json

Update Vue to official 3.0 release

feat(deps): updated dependencies Vue 3 and Readme

---

.eslintrc.js
dev/typescript/App.vue
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/composables/input-events.ts
src/styles/themes/default.scss
src/useApi.ts
tsconfig.json

/kind feature
Adds custom fields via slot
Fixes #95
```release-note
```
```docs
```

feat(custom-field): added custom field support via scoped slots

---

.github/workflows/ci.yml
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue

>
/kind bug
Fixes #129 
```release-note
```
```docs
```

fix(options): added condition for empty options

---

dev/typescript/main.ts
src/components/checkbox-input/CheckboxInput.vue

fix(checkbox): added checked prop

---

.github/workflows/release.yml
README.md
package-lock.json
package.json

/kind cleanup
Bringing back semantic release ci worflow after manually upgrading next branch to 3.0.0

Semantic release next

---

dev/typescript/App.vue
dev/typescript/main.ts
package-lock.json
package.json
rollup.config.js
src/components/checkbox-input/CheckboxInput.vue
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/components/number-input/NumberInput.vue
src/components/radio-input/RadioInput.vue
src/components/select-input/SelectInput.vue
src/components/text-area-input/TextAreaInput.vue
src/components/text-input/TextInput.vue

>
/kind feature
Add Aliases option
Fixes #115

feat(build): add alias to rollup

---

package-lock.json
src/components/dynamic-form/DynamicForm.vue
vue.config.js

/kind bug
Forms should work without an explicit order property
Fixes #162 
```release-note
```
```docs
```

fix(form): add missing condition to fieldOrder sorting

---

src/composables/input-events.ts

>
/kind bug
Solve the console error.
Fixes #161

fix(events): add condition for control in input-events

---

src/core/models.ts

/kind bug
Custom Fields should also be able. to set a numeric value as default

fix(custom-field): add possibility to default number value

---

dev/typescript/App.vue
src/components/checkbox-input/CheckboxInput.vue
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/composables/input-events.ts
src/core/utils/helpers.ts

>
/kind cleanup
I wasn't happy with the events emitted so I made the correct refactor
Fixes #159 
```release-note
```
```docs
```

feat(inputs): improve event handling

---

.github/workflows/ci.yml
src/components/dynamic-input/DynamicInput.vue

/kind bug
After events being refactor, custom fields were failing

fix(custom): fix change event on custom field

---

dev/typescript/App.vue
dev/typescript/main.ts
package-lock.json
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/core/models.ts

feat(forms): added CustomStyles attr for forms and inputs

---

src/components/checkbox-input/CheckboxInput.vue
src/composables/input-events.ts

>
/kind bug
Checkboxes where returning the event instead of the value

fix(checkbox): added back onCheck event

---

src/components/dynamic-input/DynamicInput.vue
src/styles/themes/default.scss

fix(input): remove label when empty

---

src/components/dynamic-form/DynamicForm.vue

>
/kind bug
Cache for. change detection needs to be updated after each iteration

fix: update cache after change detection succeed.

---

dev/vue/App.vue
src/components/checkbox-input/CheckboxInput.vue
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/components/number-input/NumberInput.vue
src/components/radio-input/RadioInput.vue
src/components/select-input/SelectInput.vue
src/components/text-area-input/TextAreaInput.vue
src/components/text-input/TextInput.vue
src/composables/input-events.ts
src/composables/use-debounce.ts
src/core/models.ts

>
/kind cleanup
Remove warnings

fix: removed all warnings

---

package-lock.json
package.json
src/components/checkbox-input/CheckboxInput.vue
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/components/number-input/NumberInput.vue
src/components/radio-input/RadioInput.vue
src/components/select-input/SelectInput.vue
src/components/text-area-input/TextAreaInput.vue
src/components/text-input/TextInput.vue
src/composables/input-events.ts
src/composables/use-validation.ts
src/dynamicForms.ts
src/shims-vue.d.ts
src/useApi.ts

Testing [vue-demi](https://github.com/antfu/vue-demi)

feat(installation): test vue-demi for isomorphic installation

---

dev/typescript/App.vue
package.json
rollup.config.js
src/components/checkbox-input/CheckboxInput.vue
src/components/dynamic-form/DynamicForm.vue
src/components/dynamic-input/DynamicInput.vue
src/components/number-input/NumberInput.vue
src/components/radio-input/RadioInput.vue
src/components/select-input/SelectInput.vue
src/components/text-area-input/TextAreaInput.vue
src/components/text-input/TextInput.vue
src/composables/input-events.ts
src/composables/use-validation.ts
src/core/models.ts
src/dynamicForms.ts
src/shims-vue.d.ts
src/useApi.ts

>
/kind bug
`vue-demi` and `rolloup-plugin-vue` lead to an Invalid VNode error breaking the lib

fix(build): remove vue-demi

---

netlify.toml

fix(deploy): added redirect in netlify config for demo pages

---

demos/vue-3/src/views/Basic.vue
src/dynamicForms.ts

>
/kind bug
Fixes #227 
```release-note
```
```docs
```

Pascalcase Component naming

---

.github/workflows/ci.yml
.github/workflows/release.yml
.npmignore
api-extractor.json
src/components/dynamic-form/DynamicForm.vue
tsconfig.json
vite-lib.config.ts

>
/kind bug
Declaration types were not created successfully on the npm final package.
Fixes #261

fix: dts generation on dist

---

docs/guide/theming/basic.md

Fix typo in `docs/guide/theming/basic.md`
>
> /kind bug
> /kind design
```release-note
```
```docs
```

chore: fix typo

---

README.md

fix typo in readme.md
>
> /kind bug
> /kind design
Fixes #
```release-note
```
```docs
```

Update readme - spell check
